### ISSUE TITLE
After Updating to latest  Version tests fail

### ISSUE THREAD

**Issue by BlairAllegroTech** [rickmugridge/mismatched#2]
After updating to the latest version of mismatched  from version 2.8.2. to 2.9.0 all my tests failed.

This is likely because `ts-prelude` is listed as a DEV dependency but is required for tests to run.
 - Suggest making `ts-prelude` a prod or peer dependency 

## Example Error Output
```
  ● Test suite failed to run

    Cannot find module 'prelude-ts' from 'node_modules/mismatched/dist/src/diff/arrayDiff.js'

    Require stack:
      node_modules/mismatched/dist/src/diff/arrayDiff.js
      node_modules/mismatched/dist/src/matcher/ArrayMatcher.js
      node_modules/mismatched/dist/src/match.js
      node_modules/mismatched/dist/src/index.js
      src/pipIotBridge/converters/peopleSense.micro.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/mismatched/src/diff/arrayDiff.ts:5:1)
```

## Workaround
Install `ts-prelude` into your project then tests will run

**Comment by rickmugridge** [comment]
Fixed, thanks Blair/
